feat: tipping
usedispatch/townsquare pull request #19
Opened 2023-08-21 20:22 UTC by 0xPratik

2023-08-24 19:46 UTC, tj-dispatch requested changes
Please separate everything out into more readable components and functions then re-submit! Gotta do it b/c it's too hard to review otherwise.

2023-08-24 19:46 UTC, tj-dispatch commented on src/view/com/modals/TippingModal.web.tsx
> +  ({
remember, named functions not arrow functions here.

2023-08-25 17:27 UTC, tj-dispatch requested changes
looking better!

2023-08-25 17:27 UTC, tj-dispatch commented on src/view/com/util/forms/TipdropdownBtn.tsx
> +          if (isBtn(item)) {
put this into its own component

2023-08-25 17:27 UTC, tj-dispatch commented on src/view/com/util/post-ctrls/PostCtrls.tsx
> +            store.shell.openModal({
separate this out so it's not so much copy/pasta

2023-08-25 17:27 UTC, tj-dispatch commented on src/view/com/wallet/useSplxWallet.tsx
> -import { useEffect } from 'react';
What changed here? Please undo these formatting changes and resubmit so I can see the actual change (if there is one)

2023-08-25 17:27 UTC, tj-dispatch commented on src/state/splx-wallet.ts
>  import { debouncer } from "../lib/splx-utils/functions";
What changed here? Please remove all of these styling changes and resubmit so I can review.

2023-08-25 18:23 UTC, 0xPratik commented on src/view/com/util/forms/TipdropdownBtn.tsx
> +          if (isBtn(item)) {
This will probably take some time i broke it down to a component but the Ui is getting broken so i reverted back it to how it was btw it's the bluesky guys code i didn't write this

2023-08-25 18:25 UTC, tj-dispatch commented
Ahh, okay, got it

On Fri, Aug 25, 2023 at 2:24 PM Pratik Saria ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/view/com/util/forms/TipdropdownBtn.tsx
> <https://github.com/usedispatch/townsquare/pull/19#discussion_r1306007352>
> :
>
> > +        // props, and always have an explicit label
> +        accessibilityRole="button"
> +        accessibilityLabel="Toggle dropdown"
> +        accessibilityHint=""
> +      >
> +        <View style={[styles.bg]} />
> +      </TouchableWithoutFeedback>
> +      <View
> +        style={[
> +          styles.menu,
> +          { left: x, top: y, width },
> +          dropDownBackgroundColor,
> +        ]}
> +      >
> +        {items.map((item, index) => {
> +          if (isBtn(item)) {
>
> This will probably take some time i broke it down to a component but the
> Ui is getting broken so i reverted back it to how it was btw it's the
> bluesky guys code i didn't write this
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/usedispatch/townsquare/pull/19#discussion_r1306007352>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3NU4I2R75XCC3GR4JMB6FTXXDUURANCNFSM6AAAAAA3Y4WIMM>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-08-28 19:34 UTC, merged